name: abs

dependencies:
   - base

   - QuickCheck
   - array
   - attoparsec
   - bytestring
   - containers
   - deepseq
   - extra
   - fgl
   - hashable
   - heaps
   - integer-logarithms
   - lens
   - massiv
   - mono-traversable
   - mtl
   - mutable-containers
   - mwc-random
   - parallel
   - parsec
   - primitive
   - psqueues
   - random
   - reflection
   - template-haskell
   - text
   - tf-random
   - transformers
   - unboxing-vector
   - unordered-containers
   - utility-ht
   - vector
   - vector-algorithms
   - vector-th-unbox

language: GHC2021

# DRY for package.yaml executables:
# <https://www.reddit.com/r/haskell/comments/haeqin/dry_for_packageyaml_executables/>
_exe-defs: &exe-defaults
  # dependencies:
  # - abs
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall # all warnings
  other-modules: []

# REMARK: See `README` for the langauge server support.
executables:
  practicea-exe:
    <<: *exe-defaults
    source-dirs: "practicea"
    main: Main.hs

  abc049c-exe:
    <<: *exe-defaults
    source-dirs: "abc049c"
    main: Main.hs

  abc081a-exe:
    <<: *exe-defaults
    source-dirs: "abc081a"
    main: Main.hs

  abc081b-exe:
    <<: *exe-defaults
    source-dirs: "abc081b"
    main: Main.hs

  abc083b-exe:
    <<: *exe-defaults
    source-dirs: "abc083b"
    main: Main.hs

  abc085b-exe:
    <<: *exe-defaults
    source-dirs: "abc085b"
    main: Main.hs

  abc085c-exe:
    <<: *exe-defaults
    source-dirs: "abc085c"
    main: Main.hs

  abc086a-exe:
    <<: *exe-defaults
    source-dirs: "abc086a"
    main: Main.hs
  
  abc086c-exe:
    <<: *exe-defaults
    source-dirs: "abc086c"
    main: Main.hs

  abc087b-exe:
    <<: *exe-defaults
    source-dirs: "abc087b"
    main: Main.hs

  abc088b-exe:
    <<: *exe-defaults
    source-dirs: "abc088b"
    main: Main.hs
